apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
  namespace: k8stestspace
  labels:
    app: bankapp
spec:
  selector:
    matchLabels:
      app: bankapp
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
        - name: bankapp
          image: 'spramkumar1989/bankapp-v1:latest'
          resources:
            requests:
              cpu: '2'
            limits:
              cpu: '2'
          volumeMounts: 
            -  name: common-config
               mountPath: "/app/config"
            -  name: bank-config
               mountPath: "/app/config/app"
      volumes:
        - name: common-config
          configMap:
            name: common-config
        - name: bank-config
          configMap:
            name: bank-config
